all:
	gcc -Wall -o main.o -c main.c
	gcc -Wall -o carte.o -c carte.c
	gcc -Wall -o personnage.o -c personnage.c
	gcc -Wall -o historique.o -c historique.c
	gcc -Wall -o score.o -c score.c



	gcc -o main *.o